name: Qiita Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  QIITA_USER_ID: ${{ secrets.QIITA_USER_ID }}

jobs:
  qiita_sync_check:
    name: Run qiita-sync sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install qiita-sync
        run: |
          python -m pip install qiita-sync

      - name: Git
        run: |
          for FILE_PATH in articles/*.md; do
            if [ -f "$FILE_PATH" ]; then
              FILE_CONTENT=$(jq -Rs . < $FILE_PATH)
              TARGET_TITLE=$(grep -oP '(?<=title: ).*' $FILE_PATH)
              TARGET_TITLE_ESCAPED=$(echo "$TARGET_TITLE" | jq -Rs .)
      
              ARTICLES=$(curl -s "https://qiita.com/api/v2/users/${{ env.QIITA_USER_ID }}/items" -H "Authorization: Bearer ${{ secrets.QIITA_ACCESS_TOKEN }}")
              ARTICLE_ID=$(echo $ARTICLES | jq -r ".[] | select(.title == $TARGET_TITLE_ESCAPED) | .id")
              QIITA_CONTENT=$(echo $ARTICLES | jq -r ".[] | select(.title == $TARGET_TITLE_ESCAPED) | .body")
      
              if [ "$FILE_CONTENT" != "$QIITA_CONTENT" ]; then
                if [ ! -z "$ARTICLE_ID" ]; then
                  curl -X PATCH "https://qiita.com/api/v2/items/$ARTICLE_ID" \
                    -H "Authorization: Bearer ${{ secrets.QIITA_ACCESS_TOKEN }}" \
                    -H "Content-Type: application/json" \
                    -d "{\"body\": $FILE_CONTENT}"
                else
                  curl -X POST "https://qiita.com/api/v2/items" \
                    -H "Authorization: Bearer ${{ secrets.QIITA_ACCESS_TOKEN }}" \
                    -H "Content-Type: application/json" \
                    -d "{\"body\": $FILE_CONTENT, \"title\": $TARGET_TITLE_ESCAPED, \"tags\": [{\"name\": \"sample\"}]}"
                fi
              fi
            fi
          done
          
        shell: bash
        