name: Qiita Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  QIITA_USER_ID: ${{ secrets.QIITA_USER_ID }}

jobs:
  qiita_sync_check:
    name: Run qiita-sync sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install qiita-sync
        run: |
          python -m pip install qiita-sync

      - name: Git
        run: |
          for DIR in articles resources; do
            for FILE_PATH in $DIR/*; do
            
              FILE_CONTENT=$(cat $FILE_PATH)
              TARGET_TITLE=$(head -n 1 $FILE_PATH | sed 's/^# //')

              ARTICLES=$(curl -s "https://qiita.com/api/v2/users/${{ env.QIITA_USER_ID }}/items" -H "Authorization: Bearer ${{ secrets.QIITA_ACCESS_TOKEN }}")
              ARTICLE_ID=$(echo $ARTICLES | jq -r ".[] | select(.title == \"$TARGET_TITLE\") | .id")
              QIITA_CONTENT=$(echo $ARTICLES | jq -r ".[] | select(.title == \"$TARGET_TITLE\") | .body")

              if [ "$FILE_CONTENT" != "$QIITA_CONTENT" ]; then
                if [ ! -z "$ARTICLE_ID" ]; then
                  curl -X PATCH "https://qiita.com/api/v2/items/$ARTICLE_ID" \
                    -H "Authorization: Bearer ${{ secrets.QIITA_ACCESS_TOKEN }}" \
                    -H "Content-Type: application/json" \
                    -d "{\"body\": \"$FILE_CONTENT\"}"
                else
                  curl -X POST "https://qiita.com/api/v2/items" \
                    -H "Authorization: Bearer ${{ secrets.QIITA_ACCESS_TOKEN }}" \
                    -H "Content-Type: application/json" \
                    -d "{\"body\": \"$FILE_CONTENT\", \"title\": \"$TARGET_TITLE\", \"tags\": [{\"name\": \"sample\"}]}"
                fi
              fi

            done
          done
          
        shell: bash
        